Update terraform_deployment.yml

diff --git a/.github/workflows/terraform_deployment.yml b/.github/workflows/terraform_deployment.yml
--- a/.github/workflows/terraform_deployment.yml
+++ b/.github/workflows/terraform_deployment.yml
@@ -3,7 +3,7 @@ name: Terraform Code For ECS Deployment
 on:
   push:
     branches:
-      - main
+      - blue-green
     paths:
       - "Terraform-Deployment/**"
 
@@ -11,6 +11,9 @@ env:
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   AWS_REGION: ${{ secrets.AWS_REGION }}
+  S3_BUCKET: technova-codedeploy-bucket
+  CODEDEPLOY_APP: technova-codedeploy
+  CODEDEPLOY_GROUP: technova-deploy-group
 
 jobs:
   terraform-deploy:
@@ -30,11 +33,6 @@ jobs:
         working-directory: ./Terraform-Deployment
         run: terraform init
 
-      - name: Terraform Code Format Validation
-        working-directory: ./Terraform-Deployment
-        run: terraform fmt -check
-        continue-on-error: true
-
       - name: Terraform Code Validation
         working-directory: ./Terraform-Deployment
         run: terraform validate
@@ -46,3 +44,38 @@ jobs:
       - name: Apply Terraform Changes
         working-directory: ./Terraform-Deployment
         run: terraform apply -auto-approve
+
+      - name: Generate AppSpec and Upload to S3
+        working-directory: Deployment_infra
+        run: |
+          TASK_ARN=$(terraform output -raw latest_task_definition_arn)
+          echo "Task ARN from terraform: $TASK_ARN"
+          if [ -z "$TASK_ARN" ]; then
+            echo "Error: TASK_ARN is empty!"
+            exit 1
+          fi
+          
+          cat <<EOF > appspec.yaml
+          version: 1
+          Resources:
+            - TargetService:
+                Type: AWS::ECS::Service
+                Properties:
+                  TaskDefinition: $TASK_ARN
+                  LoadBalancerInfo:
+                    ContainerName: "technova"
+                    ContainerPort: 3000
+          EOF
+
+          echo "Generated AppSpec content:"
+          cat appspec.yaml
+
+          aws s3 cp appspec.yaml s3://${S3_BUCKET}/appspec.yaml || { echo "Failed to upload AppSpec to S3"; exit 1; }
+
+      - name: Trigger CodeDeploy Deployment
+        run: |
+          aws deploy create-deployment \
+            --application-name $CODEDEPLOY_APP \
+            --deployment-group-name $CODEDEPLOY_GROUP \
+            --s3-location bucket=$S3_BUCKET,bundleType=YAML,key=appspec.yaml \
+            --description "Deploying latest task" || { echo "CodeDeploy deployment failed"; exit 1; }
